import { SignInButton, useUser } from '@clerk/nextjs';
import dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime';
import { type NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

dayjs.extend(relativeTime);

import { LoadingPage } from '@/components/loadingSpinner/LoadingSpinner';
import { RouterOutputs, api } from '@/utils/api';

const CreatePostWizard = () => {
  const { user } = useUser();

  if (!user) return null;

  return (
    <div className='flex w-full gap-3'>
      <Image width={56} height={56} src={user.profileImageUrl} alt='Profile image' className='h-14 w-14 rounded-full' />
      <input placeholder='Type some emojis!' className='grow bg-transparent outline-none' />
    </div>
  );
};

type PostWithUser = RouterOutputs['posts']['getAll'][number];

const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  return (
    <div className='flex gap-3 border-b border-slate-400 p-4'>
      <Image
        width={56}
        height={56}
        src={author.profileImageUrl}
        className='h-14 w-14 rounded-full'
        alt={`@${author.username as string}'s profile picture`}
      />
      <div className='flex flex-col'>
        <div className='flex gap-1 text-slate-300'>
          <span>{`@${author.username as string}`}</span>
          <span className='font-thin'> · </span>
          <span className='font-thin'>{dayjs(post.createdAt).fromNow()}</span>
        </div>
        <span>{post.content}</span>
      </div>
    </div>
  );
};

const Feed = () => {
  const { data, isLoading: postsLoading } = api.posts.getAll.useQuery();

  if (postsLoading) return <LoadingPage />;

  if (!data) return <div>Something went wrong</div>;

  return (
    <div className='flex flex-col'>
      {data?.map((fullPost) => (
        <PostView {...fullPost} key={fullPost.post.id} />
      ))}
    </div>
  );
};

const Home: NextPage = () => {
  const { isLoaded: userLoaded, isSignedIn } = useUser();

  // Start fetching ASAP
  api.posts.getAll.useQuery();

  // Return empty div id BOTH aren't loaded, since user tends to load faster
  if (!userLoaded) return <></>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex h-screen justify-center'>
        <div className='h-full w-full border-x border-slate-400 md:max-w-2xl'>
          <div className='flex border-b border-slate-400 p-4 '>
            {!isSignedIn && (
              <div className='flex justify-center'>
                <SignInButton />
              </div>
            )}
            {isSignedIn && <CreatePostWizard />}
          </div>
          <Feed />
        </div>
      </main>
    </>
  );
};

export default Home;
